### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by Gaai** [weichenlin306/u8g2_font_tools#1]
Hi there, 
Looks like a nice tool. Would be very helpful if the menus could be translated to English ;)
Or you explain in english what each menu/button/option does.

**Comment by weichenlin306** [comment]
I apologize for the delayed response.
Perhaps I can get back to you for this translation when I am not occupied with work.

**Comment by weichenlin306** [comment]
> Hi there, Looks like a nice tool. Would be very helpful if the menus could be translated to English ;) Or you explain in english what each menu/button/option does.

English translated version has been uploaded!

**Comment by Gaai** [comment]
Cool. I'll check it out when I'm back home again.
